# Generated by Django 4.2.21 on 2025-12-01 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='api_provider',
            field=models.CharField(default='deepseek', max_length=50, verbose_name='API Provider'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='frequency_penalty',
            field=models.FloatField(default=0.0, verbose_name='Frequency Penalty'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='max_tokens',
            field=models.IntegerField(default=2000, verbose_name='Max Tokens'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='presence_penalty',
            field=models.FloatField(default=0.0, verbose_name='Presence Penalty'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='temperature',
            field=models.FloatField(default=0.7, verbose_name='Temperature'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='theme',
            field=models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', max_length=20, verbose_name='Theme'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='top_p',
            field=models.FloatField(default=1.0, verbose_name='Top P'),
        ),
    ]
