# Generated by Django 5.2.8 on 2025-12-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_usersettings_api_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='_encrypted_qwen_api_key',
            field=models.TextField(blank=True, default='', verbose_name='Qwen API Key (加密)'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='api_provider',
            field=models.CharField(choices=[('deepseek', 'DeepSeek'), ('qwen', 'Qwen (通义千问)')], default='deepseek', max_length=50, verbose_name='API Provider'),
        ),
    ]
