# Generated by Django 5.2.8 on 2026-02-11

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_add_qwen_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEditPrefill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('prompt_text', models.TextField(max_length=1000, verbose_name='提示文本')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认（增加细节）')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_prefills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '编辑指引预设',
                'verbose_name_plural': '编辑指引预设',
                'ordering': ['order', 'created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]

