# Generated by Django 5.2.11 on 2026-02-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_usereditprefill_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='api_provider',
            field=models.CharField(choices=[('deepseek', 'DeepSeek'), ('qwen', 'Qwen (通义千问)'), ('openrouter', 'OpenRouter')], default='deepseek', max_length=50, verbose_name='API Provider'),
        ),
    ]
