# Generated by Django 4.2.21 on 2025-09-11 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='作品标题')),
                ('synopsis', models.TextField(blank=True, verbose_name='作品大纲')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '作品',
                'verbose_name_plural': '作品',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LoreEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='条目名称')),
                ('description', models.TextField(verbose_name='详细描述')),
                ('triggers', models.JSONField(default=list, help_text='当内容中包含这些词时会触发此条目', verbose_name='触发词')),
                ('extra_triggers', models.JSONField(default=list, help_text='用户自定义的额外触发词', verbose_name='额外触发词')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lore_entries', to='works.work', verbose_name='所属作品')),
            ],
            options={
                'verbose_name': '世界观条目',
                'verbose_name_plural': '世界观条目',
                'ordering': ['work', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='章节标题')),
                ('content', models.TextField(blank=True, verbose_name='章节内容')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('summary', models.TextField(blank=True, verbose_name='章节摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_autosave', models.DateTimeField(auto_now=True, verbose_name='最后自动保存时间')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='works.work', verbose_name='所属作品')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
                'ordering': ['work', 'order'],
                'unique_together': {('work', 'order')},
            },
        ),
    ]
