# Generated by Django 4.2.21 on 2025-09-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='act',
            field=models.PositiveIntegerField(default=1, verbose_name='卷数'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='act_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='卷名'),
        ),
    ]
