# Generated by Django 4.2.21 on 2025-09-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_add_act_structure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['work', 'act', 'chapter_number'], 'verbose_name': '章节', 'verbose_name_plural': '章节'},
        ),
        migrations.AddField(
            model_name='chapter',
            name='chapter_number',
            field=models.PositiveIntegerField(default=1, verbose_name='章节号'),
        ),
    ]
