# Generated by Django 4.2.21 on 2025-09-13 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_alter_chapter_options_chapter_chapter_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='卷名')),
                ('order', models.PositiveIntegerField(verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acts', to='works.work', verbose_name='所属作品')),
            ],
            options={
                'verbose_name': '卷',
                'verbose_name_plural': '卷',
                'ordering': ['work', 'order'],
                'unique_together': {('work', 'order')},
            },
        ),
    ]
