# Generated by Django 4.2.21 on 2025-09-13 02:52

from django.db import migrations


def _table_columns(schema_editor, table_name):
    with schema_editor.connection.cursor() as cursor:
        return {col.name for col in schema_editor.connection.introspection.get_table_description(cursor, table_name)}


def populate_acts_from_chapters(apps, schema_editor):
    """Create Act objects based on existing chapter data"""
    Work = apps.get_model('works', 'Work')
    Act = apps.get_model('works', 'Act')
    has_act_name = 'act_name' in _table_columns(schema_editor, 'works_chapter')
    
    for work in Work.objects.all():
        # Get all unique act numbers for this work
        act_numbers = set(work.chapters.values_list('act', flat=True))
        
        for act_number in act_numbers:
            if act_number and act_number > 0:  # Skip invalid act numbers
                act_name = f'第{act_number}卷'
                if has_act_name:
                    # Get act name from the first chapter with this act number
                    chapter_with_name = (
                        work.chapters
                        .filter(act=act_number, act_name__isnull=False)
                        .exclude(act_name='')
                        .first()
                    )
                    if chapter_with_name:
                        act_name = chapter_with_name.act_name
                
                # Create the Act object
                Act.objects.get_or_create(
                    work=work,
                    order=act_number,
                    defaults={'name': act_name}
                )


def reverse_populate_acts(apps, schema_editor):
    """Remove all Act objects"""
    Act = apps.get_model('works', 'Act')
    Act.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_add_act_model'),
    ]

    operations = [
        migrations.RunPython(populate_acts_from_chapters, reverse_populate_acts),
    ]
