# Generated by Django 4.2.21 on 2025-09-13 02:53

from django.db import migrations, models
import django.db.models.deletion


def convert_chapter_acts_to_foreign_keys(apps, schema_editor):
    """Convert chapter.act from integer to foreign key reference"""
    Chapter = apps.get_model('works', 'Chapter')
    Act = apps.get_model('works', 'Act')
    
    # Add a temporary field to store the Act foreign key
    schema_editor.execute(
        'ALTER TABLE works_chapter ADD COLUMN act_fk_id BIGINT REFERENCES works_act(id)'
    )
    
    # Update each chapter to point to the correct Act
    for chapter in Chapter.objects.all():
        act_obj = Act.objects.filter(work=chapter.work, order=chapter.act).first()
        if act_obj:
            schema_editor.execute(
                'UPDATE works_chapter SET act_fk_id = %s WHERE id = %s',
                [act_obj.id, chapter.id]
            )
    
    # Remove the old act field and rename the new one
    schema_editor.execute('ALTER TABLE works_chapter DROP COLUMN act')
    schema_editor.execute('ALTER TABLE works_chapter DROP COLUMN act_name')
    schema_editor.execute('ALTER TABLE works_chapter RENAME COLUMN act_fk_id TO act_id')


def reverse_convert_chapter_acts(apps, schema_editor):
    """Reverse the conversion (restore integer act field)"""
    Chapter = apps.get_model('works', 'Chapter')
    Act = apps.get_model('works', 'Act')
    
    # Add back the integer act field
    schema_editor.execute('ALTER TABLE works_chapter ADD COLUMN act_int INTEGER')
    schema_editor.execute('ALTER TABLE works_chapter ADD COLUMN act_name VARCHAR(100)')
    
    # Convert foreign keys back to integers
    for chapter in Chapter.objects.all():
        if hasattr(chapter, 'act_id') and chapter.act_id:
            act_obj = Act.objects.filter(id=chapter.act_id).first()
            if act_obj:
                schema_editor.execute(
                    'UPDATE works_chapter SET act_int = %s, act_name = %s WHERE id = %s',
                    [act_obj.order, act_obj.name, chapter.id]
                )
    
    # Drop foreign key field and rename integer field
    schema_editor.execute('ALTER TABLE works_chapter DROP COLUMN act_id')
    schema_editor.execute('ALTER TABLE works_chapter RENAME COLUMN act_int TO act')


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_populate_acts'),
    ]

    operations = [
        migrations.RunPython(convert_chapter_acts_to_foreign_keys, reverse_convert_chapter_acts),
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['act__order', 'chapter_number'], 'verbose_name': '章节', 'verbose_name_plural': '章节'},
        ),
    ]
