# Generated by Django 4.2.21 on 2025-09-15 01:11

import apps.works.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_convert_chapter_act_to_foreign_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='id',
            field=models.BigIntegerField(default=apps.works.models.generate_large_id, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='id',
            field=models.BigIntegerField(default=apps.works.models.generate_large_id, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loreentry',
            name='id',
            field=models.BigIntegerField(default=apps.works.models.generate_large_id, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='work',
            name='id',
            field=models.BigIntegerField(default=apps.works.models.generate_large_id, primary_key=True, serialize=False),
        ),
    ]
