# Generated by Django 4.2.21 on 2025-10-21 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0007_add_large_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='act_name',
        ),
        migrations.AlterField(
            model_name='chapter',
            name='act',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='works.act', verbose_name='所属卷'),
        ),
    ]
