# Generated by Django 4.2.21 on 2025-10-21 09:14
# Note: This migration is a no-op because its operations were already performed in migration 0006

from django.db import migrations


def noop(apps, schema_editor):
    """Do nothing - this migration's work was already done in 0006"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0007_add_large_ids'),
    ]

    operations = [
        migrations.RunPython(noop, noop),
    ]
