# Generated by Django 4.2.21 on 2025-11-21 01:59

import apps.works.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('works', '0008_remove_chapter_act_name_alter_chapter_act'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingStyle',
            fields=[
                ('id', models.BigIntegerField(default=apps.works.models.generate_large_id, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='风格名称')),
                ('style_data', models.TextField(help_text='完整的风格描述文本', verbose_name='风格内容')),
                ('analysis_result', models.JSONField(blank=True, help_text='AI分析的结构化数据，包含多个维度和示例', null=True, verbose_name='分析结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_styles', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '写作风格',
                'verbose_name_plural': '写作风格',
                'ordering': ['user', '-updated_at'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
