# Generated by Django 4.2.21 on 2025-12-15 06:36

from django.db import migrations


def renumber_all_chapters(apps, schema_editor):
    """Renumber all chapters to be continuous across acts"""
    from django.db import connection

    with connection.cursor() as cursor:
        # Get all works
        cursor.execute("SELECT id FROM works_work")
        work_ids = cursor.fetchall()

        for (work_id,) in work_ids:
            # Renumber chapters continuously for this work
            cursor.execute("""
                WITH numbered_chapters AS (
                    SELECT id, ROW_NUMBER() OVER (ORDER BY "order") as new_num
                    FROM works_chapter
                    WHERE work_id = %s
                )
                UPDATE works_chapter
                SET chapter_number = nc.new_num
                FROM numbered_chapters nc
                WHERE works_chapter.id = nc.id
            """, [work_id])


def reverse_renumber_chapters(apps, schema_editor):
    """Reverse operation: renumber chapters within each act"""
    from django.db import connection

    # Use raw SQL for reverse operation due to migration model limitations
    with connection.cursor() as cursor:
        # Get all works
        cursor.execute("SELECT DISTINCT work_id FROM works_chapter")
        work_ids = cursor.fetchall()

        for (work_id,) in work_ids:
            # Get all acts for this work
            cursor.execute("SELECT id FROM works_act WHERE work_id = %s ORDER BY order", [work_id])
            act_ids = cursor.fetchall()

            for (act_id,) in act_ids:
                # Renumber chapters within this act
                cursor.execute("""
                    WITH numbered_chapters AS (
                        SELECT id, ROW_NUMBER() OVER (ORDER BY "order") as new_num
                        FROM works_chapter
                        WHERE work_id = %s AND act_id = %s
                    )
                    UPDATE works_chapter
                    SET chapter_number = nc.new_num
                    FROM numbered_chapters nc
                    WHERE works_chapter.id = nc.id
                """, [work_id, act_id])


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0009_writingstyle'),
    ]

    operations = [
        migrations.RunPython(renumber_all_chapters, reverse_renumber_chapters),
    ]
