# Generated by Django 5.2.11 on 2026-02-27 05:38
# Note: This migration is intentionally a no-op for schema safety.
# Similar to historical handling in works migration 0008 (commit 1901dca),
# the conflicting chapter act_name removal had effectively already happened.

from django.db import migrations


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0017_work_work_type'),
    ]

    operations = [
        migrations.RunPython(noop, noop),
    ]
