# Generated by Django 4.2.21 on 2025-09-11 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='笔记内容')),
                ('color', models.CharField(choices=[('#f59e0b', '黄色'), ('#ef4444', '红色'), ('#10b981', '绿色'), ('#3b82f6', '蓝色'), ('#8b5cf6', '紫色'), ('#f97316', '橙色'), ('#06b6d4', '青色'), ('#84cc16', '柠檬绿')], default='#f59e0b', max_length=7, verbose_name='颜色')),
                ('text_start_position', models.PositiveIntegerField(blank=True, null=True, verbose_name='文本开始位置')),
                ('text_end_position', models.PositiveIntegerField(blank=True, null=True, verbose_name='文本结束位置')),
                ('linked_text', models.TextField(blank=True, verbose_name='关联文本')),
                ('is_ai_generated', models.BooleanField(default=False, verbose_name='AI生成')),
                ('note_type', models.CharField(choices=[('user', '用户笔记'), ('suggestion', 'AI建议'), ('reminder', '提醒'), ('character', '角色相关'), ('plot', '情节相关'), ('setting', '设定相关')], default='user', max_length=50, verbose_name='笔记类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='works.chapter', verbose_name='所属章节')),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='works.work', verbose_name='所属作品')),
            ],
            options={
                'verbose_name': '笔记',
                'verbose_name_plural': '笔记',
                'ordering': ['-created_at'],
            },
        ),
    ]
