# Generated by Django 4.2.21 on 2025-09-15 01:12

import apps.works.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.BigIntegerField(default=apps.works.models.generate_large_id, primary_key=True, serialize=False),
        ),
    ]
