# Generated by Django 4.2.21 on 2025-10-23 05:07

import apps.works.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0008_remove_chapter_act_name_alter_chapter_act'),
        ('notes', '0002_add_large_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoEdit',
            fields=[
                ('id', models.BigIntegerField(default=apps.works.models.generate_large_id, primary_key=True, serialize=False)),
                ('text_start_position', models.PositiveIntegerField(verbose_name='文本开始位置')),
                ('text_end_position', models.PositiveIntegerField(verbose_name='文本结束位置')),
                ('original_text', models.TextField(verbose_name='原始文本')),
                ('active_version_index', models.IntegerField(default=0, verbose_name='当前版本索引')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_edits', to='works.chapter', verbose_name='所属章节')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_edits', to='works.work', verbose_name='所属作品')),
            ],
            options={
                'verbose_name': '自动编辑',
                'verbose_name_plural': '自动编辑',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutoEditVersion',
            fields=[
                ('id', models.BigIntegerField(default=apps.works.models.generate_large_id, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField(verbose_name='版本号')),
                ('edited_text', models.TextField(verbose_name='编辑后文本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('auto_edit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='notes.autoedit', verbose_name='所属自动编辑')),
            ],
            options={
                'verbose_name': '自动编辑版本',
                'verbose_name_plural': '自动编辑版本',
                'ordering': ['version_number'],
                'unique_together': {('auto_edit', 'version_number')},
            },
        ),
    ]
