# Generated by Django 4.2.21 on 2025-10-23 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_autoedit_autoeditversion'),
    ]

    operations = [
        # Remove user_prompt column if it exists (from a previous failed migration attempt)
        migrations.RunSQL(
            sql="ALTER TABLE notes_autoedit DROP COLUMN IF EXISTS user_prompt;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
