# Generated by Django 4.2.21 on 2025-10-23 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20251023_1338'),
    ]

    operations = [
        # Remove color column if it exists (from a previous failed migration attempt)
        migrations.RunSQL(
            sql="ALTER TABLE notes_autoedit DROP COLUMN IF EXISTS color;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
