# Generated by Django 4.2.21 on 2025-10-23 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20251023_1342'),
    ]

    operations = [
        # Drop and recreate the AutoEdit table to ensure it matches our model exactly
        migrations.RunSQL(
            sql="""
                DROP TABLE IF EXISTS notes_autoedit CASCADE;
                CREATE TABLE notes_autoedit (
                    id BIGINT PRIMARY KEY,
                    work_id BIGINT NOT NULL REFERENCES works_work(id) ON DELETE CASCADE,
                    chapter_id BIGINT NOT NULL REFERENCES works_chapter(id) ON DELETE CASCADE,
                    text_start_position INTEGER NOT NULL,
                    text_end_position INTEGER NOT NULL,
                    original_text TEXT NOT NULL,
                    active_version_index INTEGER NOT NULL DEFAULT 0,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
                );
                CREATE INDEX notes_autoedit_work_id_idx ON notes_autoedit(work_id);
                CREATE INDEX notes_autoedit_chapter_id_idx ON notes_autoedit(chapter_id);
            """,
            reverse_sql="DROP TABLE IF EXISTS notes_autoedit CASCADE;",
        ),
    ]
