# Generated by Django 4.2.21 on 2025-09-11 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_words', models.PositiveIntegerField(default=0, verbose_name='总字数')),
                ('total_characters', models.PositiveIntegerField(default=0, verbose_name='总字符数')),
                ('words_today', models.PositiveIntegerField(default=0, verbose_name='今日字数')),
                ('words_this_week', models.PositiveIntegerField(default=0, verbose_name='本周字数')),
                ('words_this_month', models.PositiveIntegerField(default=0, verbose_name='本月字数')),
                ('ai_suggestions_generated', models.PositiveIntegerField(default=0, verbose_name='AI建议生成数')),
                ('ai_suggestions_accepted', models.PositiveIntegerField(default=0, verbose_name='AI建议采纳数')),
                ('ai_continues_used', models.PositiveIntegerField(default=0, verbose_name='AI续写使用数')),
                ('ai_chats_count', models.PositiveIntegerField(default=0, verbose_name='AI聊天次数')),
                ('avg_session_length', models.FloatField(default=0.0, verbose_name='平均写作时长(分钟)')),
                ('most_productive_hour', models.PositiveIntegerField(default=0, verbose_name='最高效时段')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('work', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='works.work', verbose_name='所属作品')),
            ],
            options={
                'verbose_name': '写作统计',
                'verbose_name_plural': '写作统计',
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(choices=[('expand', '扩展内容'), ('improve', '改进文本'), ('rewrite', '重写段落'), ('continue', '继续写作'), ('character', '角色发展'), ('plot', '情节推进'), ('dialogue', '对话优化'), ('description', '描述增强')], max_length=20, verbose_name='建议类型')),
                ('content', models.TextField(verbose_name='建议内容')),
                ('target_text', models.TextField(blank=True, verbose_name='目标文本')),
                ('text_start_position', models.PositiveIntegerField(blank=True, null=True, verbose_name='文本开始位置')),
                ('text_end_position', models.PositiveIntegerField(blank=True, null=True, verbose_name='文本结束位置')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('accepted', '已采纳'), ('rejected', '已拒绝'), ('modified', '已修改')], default='pending', max_length=20, verbose_name='状态')),
                ('trigger_reason', models.CharField(choices=[('auto', '自动触发'), ('manual', '手动请求'), ('word_count', '字数触发'), ('context', '上下文分析')], default='auto', max_length=50, verbose_name='触发原因')),
                ('context_used', models.JSONField(blank=True, default=dict, verbose_name='使用的上下文')),
                ('model_used', models.CharField(default='deepseek-chat', max_length=100, verbose_name='使用模型')),
                ('confidence_score', models.FloatField(blank=True, null=True, verbose_name='置信度分数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='works.chapter', verbose_name='所属章节')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='works.work', verbose_name='所属作品')),
            ],
            options={
                'verbose_name': 'AI建议',
                'verbose_name_plural': 'AI建议',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutoSaveHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='保存内容')),
                ('word_count', models.PositiveIntegerField(verbose_name='字数')),
                ('words_added', models.IntegerField(default=0, verbose_name='新增字数')),
                ('chars_added', models.IntegerField(default=0, verbose_name='新增字符数')),
                ('triggered_suggestion', models.BooleanField(default=False, verbose_name='触发建议生成')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='保存时间')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autosave_history', to='works.chapter', verbose_name='所属章节')),
            ],
            options={
                'verbose_name': '自动保存历史',
                'verbose_name_plural': '自动保存历史',
                'ordering': ['-created_at'],
            },
        ),
    ]
