# Generated by Django 5.2.15 on 2026-06-11 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='work',
        ),
        migrations.RemoveField(
            model_name='writingstatistics',
            name='work',
        ),
        migrations.DeleteModel(
            name='AutoSaveHistory',
        ),
        migrations.DeleteModel(
            name='Suggestion',
        ),
        migrations.DeleteModel(
            name='WritingStatistics',
        ),
    ]
