# Generated by Django 4.2.21 on 2025-10-24 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('works', '0008_remove_chapter_act_name_alter_chapter_act'),
        ('chat', '0002_alter_chatsession_chapter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='会话ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_chat_sessions', to='works.work', verbose_name='所属作品')),
            ],
            options={
                'verbose_name': '作品总览聊天会话',
                'verbose_name_plural': '作品总览聊天会话',
                'ordering': ['-updated_at'],
                'unique_together': {('work', 'user')},
            },
        ),
        migrations.CreateModel(
            name='WorkChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', 'AI助手'), ('system', '系统')], max_length=20, verbose_name='角色')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.workchatsession', verbose_name='所属会话')),
            ],
            options={
                'verbose_name': '作品总览聊天消息',
                'verbose_name_plural': '作品总览聊天消息',
                'ordering': ['created_at'],
            },
        ),
    ]
