# Generated by Django 4.2.21 on 2025-10-24 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_workchat_models'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "ALTER TABLE chat_chatsession "
                "DROP CONSTRAINT IF EXISTS chat_chatsession_work_id_chapter_id_user_id_2592621d_uniq"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterUniqueTogether(
            name='chatsession',
            unique_together={('work', 'chapter', 'user')},
        ),
    ]
