# Generated by Django 5.2.15 on 2026-06-11 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chatsession_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIRequest',
        ),
    ]
